export const PLANS = [
  {
    slug: "free",
    name: "FREE",
    price: "$0",
    period: "forever",
    desc: "Start saving today",
    features: ["Access basic offers", "3 redemptions / month", "Standard support", "Wallet basics"],
    cta: "Get Started",
    highlight: false,
    nameColor: "text-emerald-700",
  },
  {
    slug: "premium",
    name: "PREMIUM",
    price: "$9",
    period: "/ month",
    desc: "Most popular choice",
    features: ["Unlimited redemptions", "Cashback on every offer", "Priority customer support", "VIP-only weekly drops", "Multi-country access"],
    cta: "Go Premium",
    highlight: true,
    nameColor: "text-white",
  },
  {
    slug: "vip",
    name: "VIP",
    price: "$29",
    period: "/ month",
    desc: "The full luxury experience",
    features: ["Everything in Premium", "Concierge booking service", "Airport lounge access", "Exclusive luxury partners", "Complimentary birthday rewards"],
    cta: "Become VIP",
    highlight: false,
    nameColor: "text-emerald-700",
  },
];